"""Holdout verdict CLI for rule-based variant experiments.

Reads a ``results.json`` produced by any experiment script in this
directory (compare_variants_round1.py, d2_core_eval.py,
bbkc_universe_eval.py, ...) and prints a PROMOTE / CONDITIONAL / KILL /
NO_EDGE verdict for each variant against a named baseline.

The expected results.json schema matches
``logs/variant_round1/results.json``::

    {
        "<strategy_name>": {
            "per_symbol": {sym: {n_trades, total_pnl, ...}, ...},
            "aggregate":  {n_trades, total_pnl, ...}
        },
        ...
    }

This replaces ``scripts/strategy_verdict.py`` /
``scripts/donchian_verdict.py`` for holdout-era experiments. The two old
scripts still exist but read a different artifact (fine_best.json /
walkforward.json) that belongs to the pre-holdout explore pipeline;
they are documented as archived in
``docs/superpowers/specs/experiments/2026-04-14_experiment_protocol.md``.

Usage::

    python -m scripts.holdout_verdict logs/variant_round1/results.json \
        --baseline DonchianFixedRR \
        --variants DonchianFixedRRTrendFilter
    python -m scripts.holdout_verdict logs/variant_round1/results.json \
        --auto-pairs
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Tuple

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.evaluation.verdict import (
    HoldoutVerdict,
    VerdictThresholds,
    format_verdict_line,
    judge_variant_vs_baseline,
)


# Baseline mapping for --auto-pairs. A variant is expected to name its
# baseline via this lookup so the script can detect the right comparison
# without requiring the caller to type both names. Adding a new variant
# requires adding a line here so the pairing is intentional.
AUTO_PAIRS: Dict[str, str] = {
    "DonchianFixedRRTrendFilter": "DonchianFixedRR",
    "DonchianTrendFilterADX20": "DonchianTrendFilter",
    "DonchianTrendFilterADX25": "DonchianTrendFilter",
    "BBKCSqueezeHTFTrend": "BBKCSqueeze",
}


def _load_results(path: Path) -> Dict[str, Any]:
    if not path.exists():
        print(f"ERROR: results file not found: {path}")
        sys.exit(1)
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def _collect_pairs(
    results: Dict[str, Any],
    args: argparse.Namespace,
) -> List[Tuple[str, str]]:
    pairs: List[Tuple[str, str]] = []
    if args.auto_pairs:
        for variant, baseline in AUTO_PAIRS.items():
            if variant in results and baseline in results:
                pairs.append((variant, baseline))
        return pairs

    baseline = args.baseline
    if baseline is None:
        print("ERROR: --baseline is required unless --auto-pairs is given")
        sys.exit(1)
    if baseline not in results:
        print(f"ERROR: baseline '{baseline}' not in results")
        sys.exit(1)
    variants = args.variants or [
        name for name in results.keys() if name != baseline
    ]
    for v in variants:
        if v not in results:
            print(f"WARNING: variant '{v}' not in results — skipping")
            continue
        pairs.append((v, baseline))
    return pairs


def _write_markdown(
    out_path: Path,
    verdicts: List[HoldoutVerdict],
    source_path: Path,
) -> None:
    lines = [
        "# Holdout Verdict Report",
        "",
        f"**Source**: `{source_path}`",
        f"**Generated by**: `scripts/holdout_verdict.py`",
        "",
        "## Thresholds",
        "",
    ]
    t = VerdictThresholds()
    lines.append(f"- min_trades_total: {t.min_trades_total}")
    lines.append(f"- min_symbols_with_trades: {t.min_symbols_with_trades}")
    lines.append(
        f"- avg_trade_pnl_improve_eps: {t.avg_trade_pnl_improve_eps}"
    )
    lines.append(f"- mdd_improve_eps: {t.mdd_improve_eps:.1%}")
    lines.append(f"- pnl_improve_eps: {t.pnl_improve_eps}")
    lines.append(
        f"- destroyed_winner_retention_ratio: "
        f"{t.destroyed_winner_retention_ratio:.0%}"
    )
    lines.append(f"- max_destroyed_winners: {t.max_destroyed_winners}")
    lines.append(
        f"- new_symbol_prior_threshold: "
        f"{t.new_symbol_prior_threshold:.0%}"
    )
    lines.extend([
        "",
        "## Verdicts",
        "",
        "| Variant | Baseline | Verdict | Δpnl | Δavg | Δwr | Δmdd | conc | reasons |",
        "|---|---|---|---|---|---|---|---|---|",
    ])
    for v in verdicts:
        reasons = "; ".join(v.reasons) if v.reasons else ""
        lines.append(
            f"| {v.variant_name} | {v.baseline_name} | **{v.verdict}** | "
            f"{v.delta_total_pnl:+.2f} | {v.delta_avg_trade_pnl:+.2f} | "
            f"{v.delta_win_rate:+.1%} | {v.delta_max_drawdown:+.1%} | "
            f"{v.symbol_concentration:.1%} | {reasons} |"
        )
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Holdout verdict for rule-based strategy variants."
    )
    parser.add_argument(
        "results_path",
        type=Path,
        help="Path to results.json from any compare_* script",
    )
    parser.add_argument(
        "--baseline", type=str, default=None,
        help="Name of the baseline strategy in results.json",
    )
    parser.add_argument(
        "--variants", nargs="*", default=None,
        help="Variant names to judge (defaults to all non-baseline)",
    )
    parser.add_argument(
        "--auto-pairs", action="store_true",
        help="Use the built-in variant->baseline mapping",
    )
    parser.add_argument(
        "--out", type=Path, default=None,
        help="Optional path to write a markdown report",
    )
    parser.add_argument(
        "--out-json", type=Path, default=None,
        help="Optional path to write the verdict list as JSON",
    )
    args = parser.parse_args()

    results = _load_results(args.results_path)
    pairs = _collect_pairs(results, args)
    if not pairs:
        print("No valid variant/baseline pairs found.")
        return 1

    verdicts: List[HoldoutVerdict] = []
    for variant_name, baseline_name in pairs:
        v = judge_variant_vs_baseline(
            variant_name=variant_name,
            variant_result=results[variant_name],
            baseline_name=baseline_name,
            baseline_result=results[baseline_name],
        )
        verdicts.append(v)
        print(format_verdict_line(v))
        for reason in v.reasons:
            print(f"    -> {reason}")

    if args.out is not None:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        _write_markdown(args.out, verdicts, args.results_path)
        print(f"\nMarkdown report: {args.out}")
    if args.out_json is not None:
        args.out_json.parent.mkdir(parents=True, exist_ok=True)
        args.out_json.write_text(
            json.dumps([v.to_dict() for v in verdicts], indent=2),
            encoding="utf-8",
        )
        print(f"JSON report: {args.out_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
