"""Metrics HTML 리포트 (Phase 2 PR 18, spec §10.6).

``render_metrics_report(run_dir, *, periods_per_year)`` →
``run_dir/charts/metrics_report.html``.

내용:
- 헤드라인: ``resolved_run_id`` + 핵심 메트릭 표
- 본문: 2단 Plotly subplot (equity / drawdown)

quantstats 의존성 없이 plotly + 단순 HTML. 더 풍부한 리포트(quantstats tearsheet 등)는
별도 통합 PR에서.

run_dir 만 입력 — 외부 cache 의존 없음 (PR 11 self-contained 와 동일 정책).
"""

from __future__ import annotations

import html as _html
import math
from decimal import Decimal
from pathlib import Path
from typing import Any

import plotly.graph_objects as go
import polars as pl
from plotly.subplots import make_subplots

from backtester.events.reader import EventLogReader
from backtester.viz.equity import build_equity_series
from backtester.viz.metrics import compute_core_metrics
from backtester.viz.run_chart import _load_run_config

# 비율(0.05 = 5%) 단위 메트릭 — 라벨에 "(%)" 붙이고 값을 ×100 으로 표기.
_PERCENT_FIELDS: frozenset[str] = frozenset(
    {"total_return", "max_drawdown_pct", "annual_volatility"}
)


def _format_metric(key: str, value: Any) -> str:
    if isinstance(value, float):
        if math.isnan(value):
            return "—"
        if key in _PERCENT_FIELDS:
            return f"{value * 100:.4f}%"
        if abs(value) >= 1000:
            return f"{value:,.2f}"
        if abs(value) >= 1:
            return f"{value:.4f}"
        return f"{value:.6f}"
    return str(value)


_METRIC_LABELS: dict[str, str] = {
    "total_return": "Total return (%)",
    "sharpe_ratio": "Sharpe",
    "sortino_ratio": "Sortino",
    "max_drawdown_pct": "Max drawdown (%)",
    "max_drawdown_duration_bars": "Max drawdown duration (bars)",
    "calmar_ratio": "Calmar",
    "annual_volatility": "Annualized volatility (%)",
    "n_periods": "n periods",
}


def _build_equity_drawdown_figure(equity_series: pl.DataFrame) -> go.Figure:
    fig = make_subplots(
        rows=2,
        cols=1,
        shared_xaxes=True,
        row_heights=[0.7, 0.3],
        vertical_spacing=0.05,
        subplot_titles=("equity", "drawdown"),
    )
    if equity_series.height > 0:
        fig.add_trace(
            go.Scatter(
                x=equity_series["timestamp"].to_list(),
                y=equity_series["equity"].to_list(),
                mode="lines",
                name="equity",
                line={"color": "steelblue"},
                showlegend=False,
            ),
            row=1,
            col=1,
        )
        if "drawdown" in equity_series.columns:
            fig.add_trace(
                go.Scatter(
                    x=equity_series["timestamp"].to_list(),
                    y=equity_series["drawdown"].to_list(),
                    mode="lines",
                    fill="tozeroy",
                    line={"color": "indianred"},
                    name="drawdown",
                    showlegend=False,
                ),
                row=2,
                col=1,
            )
    fig.update_layout(
        height=600,
        hovermode="x unified",
        margin={"l": 40, "r": 20, "t": 40, "b": 40},
    )
    return fig


def _render_html_report(
    *,
    run_id: str,
    metrics: dict[str, Any],
    fig_html: str,
) -> str:
    rows_html = "".join(
        f"<tr><td>{_html.escape(_METRIC_LABELS.get(k, k))}</td>"
        f"<td>{_html.escape(_format_metric(k, v))}</td></tr>"
        for k, v in metrics.items()
    )
    safe_run_id = _html.escape(run_id)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Backtest Report — {safe_run_id}</title>
<style>
  body {{ font-family: system-ui, sans-serif; max-width: 1100px;
         margin: 2em auto; color: #222; padding: 0 1em; }}
  h1 {{ font-size: 1.4em; margin-bottom: 0.5em; }}
  table.metrics {{ border-collapse: collapse; margin: 1em 0 2em; }}
  table.metrics td, table.metrics th {{ padding: 0.4em 1em;
                                         border: 1px solid #ddd;
                                         font-size: 0.95em; }}
  table.metrics tr:nth-child(odd) td {{ background: #fafafa; }}
  .meta {{ color: #666; font-size: 0.85em; }}
</style>
</head>
<body>
<h1>Backtest report — {safe_run_id}</h1>
<p class="meta">Generated by backtester.viz.report</p>
<h2>Core metrics</h2>
<table class="metrics">{rows_html}</table>
<h2>Equity / drawdown</h2>
{fig_html}
</body>
</html>
"""


def render_metrics_report(
    run_dir: Path,
    *,
    periods_per_year: int = 365,
) -> Path:
    """``run_dir`` 의 events.jsonl + config.{yaml,json} 으로 metrics_report.html 생성.

    EventLogReader (PR 10) → build_equity_series (PR 10) → compute_core_metrics →
    HTML 렌더. 출력 경로: ``run_dir/charts/metrics_report.html``.
    """
    config = _load_run_config(run_dir)
    initial_equity = Decimal(str(config["initial_equity"]))
    run_id = str(
        config.get("resolved_run_id") or config.get("run_id") or run_dir.name
    )

    reader = EventLogReader(run_dir / "events.jsonl")
    equity = build_equity_series(reader, initial_equity)
    metrics = compute_core_metrics(equity, periods_per_year=periods_per_year)

    fig = _build_equity_drawdown_figure(equity)
    fig_html = fig.to_html(include_plotlyjs="cdn", full_html=False)
    html_doc = _render_html_report(
        run_id=run_id, metrics=metrics, fig_html=fig_html
    )

    charts_dir = run_dir / "charts"
    charts_dir.mkdir(parents=True, exist_ok=True)
    output = charts_dir / "metrics_report.html"
    output.write_text(html_doc, encoding="utf-8")
    return output
